### ISSUE TITLE
Break lyse dependency on runmanager

### ISSUE THREAD

**Issue by philipstarkey** [labscript-suite/runmanager#98]
Lyse currently has a dependency on runmanager. As far as I can see, it's only the `runmanager.get_shot_globals()` method that is used by lyse.

This method should be relocated from runmanager to labscript-utils so that lyse does not need to depend on runmanager.

**Comment by dihm** [comment]
Tasks to finish this

- [ ] tag a new minor release that other modules can depend on
- [ ] PR for runmanager to point to new location
- [ ] PR for labscript-devices to point to new location
- [ ] PR for lyse to point to the new location.
